### ISSUE TITLE
LatexToUnicodeProcessor should not wrap long BibTeX field values automatically 

### ISSUE THREAD

**Issue by saschaszott** [renanbr/bibtex-parser#102]
The current implementation of `LatexToUnicodeProcessor.decode` leads to newline characters that are automatically added to field values if a given field value has more than 72 characters. 

This is due to the Pandoc's `wrap` option (see https://pandoc.org/MANUAL.html for details) which defaults to `auto` and results in wrapping lines to the column width specified by `--columns` (which defaults to 72 characters).

A more robust implementation should prefer the option `--wrap=none` (or alternatively `--wrap=preserve`) which does not lead to "automagically" added newline characters.

**Comment by saschaszott** [comment]
fixed by PR #103

**Comment by renanbr** [comment]
closed by #103 , released as [2.1.2](https://packagist.org/packages/renanbr/bibtex-parser#2.1.2)

**Comment by saschaszott** [comment]
> closed by #103 , released as [2.1.2](https://packagist.org/packages/renanbr/bibtex-parser#2.1.2)

Thank you!
