### ISSUE TITLE
Use `ueberdosis/pandoc` as an alternate Pandoc PHP package

### ISSUE THREAD

**Issue by extracts** [renanbr/bibtex-parser#107]
I'm currently contributing to the development of an open-source software which uses the Pandoc PHP package [ueberdosis/pandoc](https://packagist.org/packages/ueberdosis/pandoc) to facilitate PDF generation. However, this software also makes use of your `bibtex-parser` package (thanks!) which itself uses [ryakad/pandoc-php](https://packagist.org/packages/ryakad/pandoc-php) as its Pandoc PHP package.

In comparison to `ryakad/pandoc-php`, the `ueberdosis/pandoc` package seems to be better maintained but requires `symphony/process` and PHP 7.1.

Now, our issue is that both of these Pandoc PHP packages use `Pandoc\Pandoc` as their namespace so that we get namespace collisions.

Would it be possible for your `bibtex-parser` package to prefer the `ueberdosis/pandoc` package if it is installed? Thanks!

**Comment by renanbr** [comment]
closed by #108
