### ISSUE TITLE
Feature request: parse author names

### ISSUE THREAD

**Issue by andrechalom** [renanbr/bibtex-parser#15]
BibTex recognizes four parts of an author's name: First Von Last Jr.

For instance, the entry "Ludwig von Beethoven" has First: "Ludwig", von-part: "von" and Last: "Beethoven" and no Junior-part. The entry "Ford, Jr., Henry" has First: "Henry", no von-part, Last: "Ford" and Junior-part: "Jr.".

Is it possible to implement this parsing of names on `bibtex-parser`? The only PHP library I found that implements this is a very old and unmantained one, called Structures_BibTex.

References:
https://nwalsh.com/tex/texhelp/bibtx-23.html
https://github.com/pear/Structures_BibTex/blob/master/Structures/BibTex.php

**Comment by renanbr** [comment]
> Is it possible to implement this parsing of names on bibtex-parser?

Yes, it's :) I think it could be a nice feature to add to this library

Thanks for the references, the parser code is "already" done and looks good at a glance https://github.com/pear/Structures_BibTex/blob/master/Structures/BibTex.php#L619-L751

Do you think the usage below is reasonable?

```php
$listener->setTagValueProcessor(new AuthorProcessor());
```

Could you have time to start implementing this? If not, no problem

**Comment by andrechalom** [comment]
Yes, that seems very reasonable. I'll try to write a PR.
