### ISSUE TITLE
Feature request: multiple processors?

### ISSUE THREAD

**Issue by andrechalom** [renanbr/bibtex-parser#17]
I would like to use more than one Processor for `setTagValueProcessor()`. Should I

(1) write a wrapper function that calls all of the Processors? (easiest to do, but I think this generates less clear code)
(2) rewrite `setTagValueProcessor()` to accept an array of `callable`s?
(3) rewrite `setTagValueProcessor()` to accept a callable, but allow it to "stack" these callables so I can write
```php
$listener->setTagValueProcessor(new AuthorProcessor());
$listener->setTagValueProcessor(new HTMLEntitiesProcessor());
```

**Comment by renanbr** [comment]
👍 for this

I think we could:

- create a new method `$listener->addTagValueProcessor()` with the behavior you proposed
- **not** change the behavior of `$listener->setTagValueProcessor()`, it means if called it'll replace all the stack with one single processor
- mark `setTagValueProcessor` as deprecated, then drop it in the release `1.0`

WDYT?

**Comment by andrechalom** [comment]
Great thinking!
