### ISSUE TITLE
Explain how to translate LaTeX special symbols to Unicode/HTML

### ISSUE THREAD

**Issue by renanbr** [renanbr/bibtex-parser#19]
Some examples could be added to the README.md

**Comment by andrechalom** [comment]
The translation has some complexities, as braces and whitespace should be handled correctly. 
- \'e -> é
- \' e -> é
-\'{e} -> é
- \c c -> ç
- \c{c} -> ç
- \c { c } -> ç
- \cc -> error

**Comment by renanbr** [comment]
That's why I would prefer to rely on a robust library, such as [pandoc](http://pandoc.org/)

Thanks to the new future multiple tag value processors feature :smile: the docs may cover this use case. I think it's rather a documentation issue.

See this: https://github.com/renanbr/bibtex-parser/issues/5#issuecomment-271036913

**Comment by andrechalom** [comment]
Wow, this is great! I'm writing the `addTagValuesProcessor()` right now, I'll send a PR detailing some choices I made during the afternoon.

**Comment by andrechalom** [comment]
I'm unable to this this right now, but does this pandoc processing alter braces? If it does, this may require some tweaking to be used along with the AuthorProcessor. The problem is: if the HTMLEntititiesProcessor is called first, it will change the braces and then AuthorProcessor will be unable to function as expected. If AuthorProcessor is called first, the 'author' field of each entry will be an array, which must be transversed by the HTMLEntititesProcessor. (HTMLEntititesProcessor is a tentative name, of course)

**Comment by renanbr** [comment]
Good catch. In the future we can have the same problem with `keywords` also, if this tag is translated to array, for example.

As long we can see it's not that simple, we need time before making decisions about the `HTMLEntitiesProcessor` implementation and related processors. The code I have in mind is not easy as I would have wished ... processors (compatible among them) seem to be the way to make it easy.

```php
$pandoc = new Pandoc\Pandoc();
$listener->addTagValueProcessor(function (&$value, $tag) use ($pandoc) {
    $translator = function (&$text) use ($pandoc) {
        $text = $pandoc->runWith($text, [
            "from" => "latex",
            "to" => "plain" // or "html"
        ]);
    };

    if (is_array($value)) {
        array_walk($value, $translator);

        return;
    }

    call_user_func($translator, $value);
});
```

**Comment by andrechalom** [comment]
Hmm. That's right. I did some tests using pandoc now, and it really removes the braces from the text, so we must at least place an alert that the `AuthorProcessor` (and `KeywordProcessor`?) must be injected *before* the Pandoc processor (I'm also having second thoughts about calling it `HTMLEntititesProcessor`, as all your examples use `'to' => 'plain'`. Maybe `LatexProcessor` or `LatexDecodeProcessor`?).

Also, if we write a processor, should [ryakad/pandoc-php](https://github.com/ryakad/pandoc-php) be listed as a `require`ment or `suggest` in the composer.json file? I'm also not sure which fork should be used between ryakad's or ondrs'. 

It is possible to install their composer package without having pandoc binaries installed, and it simply throws a `Pandoc\PandocException` exception when called.

**Comment by renanbr** [comment]
> I'm also having second thoughts about calling it `HTMLEntititesProcessor`, as all your examples use `'to' => 'plain'`. Maybe LatexProcessor or LatexDecodeProcessor?

Me too, I would simply give coherent/meaningful names, sharing my thoughts...

- `LatexProcessor`: name is related to the content type, but what does it do finally?
- `LatexDecodeProcessor`: name is related to the action it does, but what i'll get at the end, html, plain, markdown, ... ?
- `HtmlEntitiesProcessor`: name is related to the action it does, but what are the input format?
 Should/could I use it in conjunction with the latex decode?
- `LatexToUnicodeProcessor`: name is related to the action it does, maybe it's more clear
- `LatexToHtmlProcessor`: name is related to the action it does
- `UnicodeToHtmlProcessor` (probably useless): name is related to the action it does

but not sure if it's good enough

> Also, if we write a processor, should ryakad/pandoc-php be listed as a requirement or suggest in the composer.json file? I'm also not sure which fork should be used between ryakad's or ondrs'.

I think it makes more sense if we add it as a suggestion once it's not a core dependency (but see the end of this message)

for now +1 for ryadak's, because it has less dependencies and the other one is a fork

> It is possible to install their composer package without having pandoc binaries installed, and it simply throws a Pandoc\PandocException exception when called.

IMO this isn't a problem to be handled by the bibtex parser, additionally the processors that depend on third libraries should receive an object instance ready-to-use, such as `__constructor(Pandoc\Pandoc $pandoc)`, instead of trying to create objects on the fly

**HOWEVER** I'm not sure if the workflow I have in mind will provide a good UX, because maybe there are too much steps to get things working: (1) add pandoc dependency, then (2) create a instance of `Pandoc\Pandoc()`, then (3) pass the object to the processor

`$listener->addTagValueProcessor(new LatexToUnicodeProcess())` is much more easer to understand, and as you said, pandoc wrapper will throw an exception if the binary is not available, additionally we could switch the core engine (pandoc) to another library without break the API

**Comment by andrechalom** [comment]
> `LatexToUnicodeProcessor`: name is related to the action it does, maybe it's more clear
> `LatexToHtmlProcessor`: name is related to the action it does

I think those are better, but they will simply change one line of code inside the function calling pandoc. Maybe they can be derived from a base `LatexDecodeProcessor`? Or is it too much complexity?

> for now +1 for ryadak's, because it has less dependencies and the other one is a fork

Agreed. If one of the forks were being activelly mantained, I'd go for it. But it doesn't look so.

> **HOWEVER** I'm not sure if the workflow I have in mind will provide a good UX, because maybe there are too much steps to get things working: (1) add pandoc dependency, then (2) create a instance of Pandoc\Pandoc(), then (3) pass the object to the processor

These steps you list are what I had in mind when I asked about suggest vs. require. I believe requiring will ease the work of the users that actually use these functions, whereas suggesting will be better overall for people who will not be using these functions. The question, for me, is how many of the end users would like to have an easy way of converting LaTeX code to Unicode / HTML.

**Comment by renanbr** [comment]
> Maybe they can be derived from a base LatexDecodeProcessor? Or is it too much complexity?

:+1: for a base class

> The question, for me, is how many of the end users would like to have an easy way of converting LaTeX code to Unicode / HTML.

I really don't know about people preferences :-/

Trying answering the issue question, with your rich insights, I see these steps:

1. `composer require ryakad/pandoc-php`
2. `$listener->addTagValueProcessor(new LatexToUnicodeProcess());`

Furthermore, put `ryakad/pandoc-php` in the `suggest` section fits with the composer docs
https://getcomposer.org/doc/04-schema.md#suggest

**Comment by renanbr** [comment]
I started implementing latex decoders in [latex-decoder](https://github.com/renanbr/bibtex-parser/tree/latex-decoder) branch, commit https://github.com/renanbr/bibtex-parser/commit/ae203224a565b31214eb2670f1f396b03ce84d04

Note: I'm not sure if this library should take responsibility for decoding to HTML, so I didn't implemented it.

**Comment by andrechalom** [comment]
> Note: I'm not sure if this library should take responsibility for decoding to HTML, so I didn't implemented it.

Agreed. Most developers will probably use this library in conjunction with some framework that can handle the unicode -> html translation (I'm personally using Laravel).
