### ISSUE TITLE
add start/end trigger to the listener interface

### ISSUE THREAD

**Issue by renanbr** [renanbr/bibtex-parser#2]
Listeners could be able to know when a file/string parsing has been started/finished.

It allows listeners to...
- detected the source of units found
- access the original file/string

discussion started at: https://github.com/ubergeek42/bibtex-parser/commit/3b4b07d66cedea0d72723ceb370b1921d31f269d

**Comment by renanbr** [comment]
@ubergeek42 the branch [original_entry_state](https://github.com/renanbr/bibtex-parser/tree/original_entry_state) implements the "pass original bibtex to the listener", it means that actually I'm not going to implement start/end triggers, but something much more near to what you've implemented

by the way, there are some changes I've done:
- entries have "_original" instead of "bibtex"
- the "_original" values contains always the first char as "@"
- constant name Parser::ORIGINAL_ENTRY instead of Parser::ORIG_BIBTEX

I'm planning to release the v0.2.0 next week, or before if you confirm that changes behaves as you expect.

**Comment by ubergeek42** [comment]
That looks great to me, and more sensible as well. I'll see about switching back to that branch and testing/updating my code with those minor changes and will try to let you know how it goes.

**Comment by renanbr** [comment]
as discussed, this issue was superseded by https://github.com/renanbr/bibtex-parser/commit/216caf923398704f35aa4f4be9ebda10b25669e2 and released in [0.2.0](https://github.com/renanbr/bibtex-parser/releases/tag/0.2.0)
