### ISSUE TITLE
Parsing CitationKey with : and / in them (DBPL and ACM)

### ISSUE THREAD

**Issue by pbkyriak** [renanbr/bibtex-parser#44]
DBPL citation key includes /
@article{DBLP:journals/npl/CaamanoSBD16,
ACM citation key includes .
@inproceedings{Kyriakakis:2016:EMI:3003733.3003777,

Both are not parsed.
The sulotion i tried is changing reg expr in line
https://github.com/renanbr/bibtex-parser/blob/49b46e0a012b0474761195001cdae1be898c1127/src/Parser.php#L246

to

```
if (preg_match('/^[a-zA-Z0-9_\+:\-\.\/]$/', $char)) {
```

so it will accept / and . in citation key.

**Comment by renanbr** [comment]
Thanks for catching that!

PRs are welcome, with tests and real inputs it becomes even better. Let me know if you are interested in fixing it, or just share some entries you are trying to parser, then I'll try to fix it when possible.

**Comment by renanbr** [comment]
Fixed and delivered:

- [v2.0.1](https://github.com/renanbr/bibtex-parser/releases/tag/2.0.1)
- [v1.0.4](https://github.com/renanbr/bibtex-parser/releases/tag/1.0.4)
