### ISSUE TITLE
ParserException Unexpected character '’' at line 169 column 10

### ISSUE THREAD

**Issue by mmanoeljorn** [renanbr/bibtex-parser#47]
@article{O’Connor2017653
title = "Privacy by Design: Informed Consent and Internet of Things for Smart Health ",
journal = "Procedia Computer Science ",
volume = "113",
number = "",
pages = "653 - 658",
year = "2017",
note = "The 8th International Conference on Emerging Ubiquitous Systems and Pervasive Networks (EUSPN 2017) / The 7th International Conference on Current and Future Trends of Information and Communication Technologies in Healthcare (ICTH-2017) / Affiliated Workshops ",
issn = "1877-0509",
doi = "https://doi.org/10.1016/j.procs.2017.08.329",
url = "https://www.sciencedirect.com/science/article/pii/S1877050917317398",
author = "Yvonne O’Connor and Wendy Rowan and Laura Lynch and Ciara Heavin",
keywords = "Informed Consent",
keywords = "IOT",
keywords = "Smart Health",
keywords = "Privacy by Design ",
abstract = "Abstract Check: I accept the terms and conditions and privacy policy statements associated with this technological artefact! The informed consent process is becoming more of a challenge with the emergence of Internet of Things (IoT) as data may be collected without the digital health citizen being aware. It is argued in this paper that the first phase for universal usability of IoT within the smart health domain is to ensure that digital health citizens (i.e. user of technology) are fully aware of what they are consenting to when they register an account with such technological artefacts. This point is further reinforced by the proposed ‘Privacy by Design’ requirements associated with the forthcoming General Data Protection Regulation (GDPR). This paper proposes some practical approaches which should be considered when designing and developing IoT for data collection and data sharing within the health domain. "
}

**Comment by renanbr** [comment]
Thanks for reporting this issue case.

How did you generate the entry? Manually or using some tool like Zotero/Mendeley?

The parser works fine when reading the bibtex generated by the ScienceDirect by the way.

```bib
@article{OCONNOR2017653,
title = "Privacy by Design: Informed Consent and Internet of Things for Smart Health",
journal = "Procedia Computer Science",
volume = "113",
pages = "653 - 658",
year = "2017",
note = "The 8th International Conference on Emerging Ubiquitous Systems and Pervasive Networks (EUSPN 2017) / The 7th International Conference on Current and Future Trends of Information and Communication Technologies in Healthcare (ICTH-2017) / Affiliated Workshops",
issn = "1877-0509",
doi = "https://doi.org/10.1016/j.procs.2017.08.329",
url = "http://www.sciencedirect.com/science/article/pii/S1877050917317398",
author = "Yvonne O’Connor and Wendy Rowan and Laura Lynch and Ciara Heavin",
keywords = "Informed Consent, IOT, Smart Health, Privacy by Design",
abstract = "Check: I accept the terms and conditions and privacy policy statements associated with this technological artefact! The informed consent process is becoming more of a challenge with the emergence of Internet of Things (IoT) as data may be collected without the digital health citizen being aware. It is argued in this paper that the first phase for universal usability of IoT within the smart health domain is to ensure that digital health citizens (i.e. user of technology) are fully aware of what they are consenting to when they register an account with such technological artefacts. This point is further reinforced by the proposed ‘Privacy by Design’ requirements associated with the forthcoming General Data Protection Regulation (GDPR). This paper proposes some practical approaches which should be considered when designing and developing IoT for data collection and data sharing within the health domain."
}
```

**Comment by mauriciomanoel** [comment]
Thanks, the problem was how to get the file. It's already been solved.
