### ISSUE TITLE
ParserException Unexpected character 'c' at line 13 column 200

### ISSUE THREAD

**Issue by mauriciomanoel** [renanbr/bibtex-parser#48]
https://www.sciencedirect.com/science/article/pii/S1877050917317398

@article{XU20171077,
title = "Cost Extension Control Model in Digital Context: From Continuous Cost Reduction to Value Co-creation",
journal = "Procedia Computer Science",
volume = "122",
pages = "1077 - 1083",
year = "2017",
note = "5th International Conference on Information Technology and Quantitative Management, ITQM 2017",
issn = "1877-0509",
doi = "https://doi.org/10.1016/j.procs.2017.11.476",
url = "http://www.sciencedirect.com/science/article/pii/S187705091732731X",
author = "Ling Xu and Chengxiao Zhang and Jing Guo and Xingsen Li",
keywords = "Digital, Cost control, Extension method, Big data, Value co-creation",
abstract = "Digital technology has brought about great changes in organizational structure, the way of value creation and profit-making methods, which brings new challenges to cost control based on **"chain"**. In this paper, cost control in digital context is promoted to the pattern design level, combining the cost control process and the value creation process into one. with the new characteristics of cost control, this paper puts forward that extension method can be the method and tool of cost control, and provides the optimization of strategic choice and model innovation following. Finally, the prospect of intelligent cost control based on Extenics is prospected."
}

Is it possible to ignore the **"** within the text?

**Comment by renanbr** [comment]
Quotes inside quoted contents must be escaped.

You have two options:

- Escape quotes; or
- Use braced contents.

```php
use RenanBr\BibTexParser\Listener;
use RenanBr\BibTexParser\Parser;

require 'vendor/autoload.php';

$bibtex = <<<BIBTEX
@misc{title={A "braced" content}}
@misc{title="A \"quoted\" content"}
BIBTEX;

$parser = new Parser();
$listener = new Listener();
$parser->addListener($listener);
$parser->parseString($bibtex);
$entries = $listener->export();

print_r($entries);
```

will output this:

```
Array
(
    [0] => Array
        (
            [type] => misc
            [title] => A "braced" content
            [_original] => @misc{title={A "braced" content}}
        )

    [1] => Array
        (
            [type] => misc
            [title] => A "quoted" content
            [_original] => @misc{title="A \"quoted\" content"}
        )

)
```

**Comment by mauriciomanoel** [comment]
My code:

 $parser = new Parser();             // Create a Parser
                $listener = new Listener();         // Create and configure a Listener
                $parser->addListener($listener);    // Attach the Listener to the Parser
                $parser->parseFile($file);          // or parseFile('/path/to/file.bib')
                $entries = $listener->export();

**Comment by renanbr** [comment]
@mauriciomanoel, is this issue still valid?

**Comment by mauriciomanoel** [comment]
Yes

**Comment by renanbr** [comment]
related to #57

**Comment by renanbr** [comment]
We have a new from ScienceDirect:

> Dear Renan Barbosa,
 > 
> This issue is under investigation by SD product team. Thanks.
> 
> Best Regards,
> Product Support Engineer

cc @mauriciomanoel @M4Lien

**Comment by renanbr** [comment]
unfortunately, it wasn't still fixed upstream
