### ISSUE TITLE
Dealing with double braces

### ISSUE THREAD

**Issue by felmab** [renanbr/bibtex-parser#87]
Some research units export files with double braces in it. It looks like this is an [acceptable format](https://tex.stackexchange.com/questions/327386/double-parenthesis-in-bibtex-record), however unfortunate it might be. Here is an example:

```
@article{ ISI:000440287200008,
Author = {Dubos, Nicolas and Le Viol, Isabelle and Robert, Alexandre and
   Teplitsky, Celine and Ghislain, Manon and Dehorter, Olivier and
   Julliard, Romain and Henry, Pierre Yves},
Title = {{Disentangling the effects of spring anomalies in climate and net primary
   production on body size of temperate songbirds}},
Journal = {{ECOGRAPHY}},
Year = {{2018}},
Volume = {{41}},
Number = {{8}},
Pages = {{1319-1330}},
Month = {{AUG}},
Abstract = {{Body size is implicated in individual fitness and population dynamics.
   Mounting interest is being given to the effects of environmental change [...]
   growth than food assimilation.}},
DOI = {{10.1111/ecog.03413}},
ISSN = {{0906-7590}},
EISSN = {{1600-0587}},
Keywords = {{body size; climate; birds}},
Keywords-Plus = {{TIT PARUS-MAJOR; ENVIRONMENTAL-CHANGE; GREAT TIT; NESTLING GROWTH;
   PASSERINE BIRD; BERGMANNS RULE; SURVIVAL; MODEL; MASS; ECOSYSTEMS}},
Research-Areas = {{Biodiversity \& Conservation; Environmental Sciences \& Ecology}},
Times-Cited = {{0}},
Unique-ID = {{ISI:000440287200008}},
}
```
As a result, title, year and other affected fields will contain (single) braces after parsing. Is there a way bibtex-parser can deal with this, or is this syntax simply not accepted?

(BTW we are still on version 0.5, please let me know if this has since been solved in later versions.)

**Comment by renanbr** [comment]
> As a result, title, year and other affected fields will contain (single) braces after parsing. Is there a way bibtex-parser can deal with this, or is this syntax simply not accepted?

Yes, there is :-)

The presence of braces denotes they are latex texts.

In **Version 2** you can handle them thanks to the `LatexToUnicodeProcessor`, then **the braces will be removed**, and the case will be respected, which is the intention of the braces in this case.

Note the `new ...\LatexToUnicodeProcessor()`:

```php
$listener = new \RenanBr\BibTexParser\Listener();
$listener->addProcessor(new \RenanBr\BibTexParser\Processor\LatexToUnicodeProcessor());

$parser = new \RenanBr\BibTexParser\Parser();
$parser->addListener($listener);

$parser->parseString($bibtex); // or parseFile('/path/to/file.bib')
$entries = $listener->export();
```

Take a look at https://github.com/renanbr/bibtex-parser#latex-to-unicode

> (BTW we are still on version 0.5, please let me know if this has since been solved in later versions.)

Update to version 2 as soon as possible, fewer versions aren't maintained anymore.

**Comment by felmab** [comment]
Thanks for the super fast answer and such a detailed explanation!
